table Medidas
	lineageTag: 921bfaa1-8362-4a27-9f99-93cd02c24073

	measure 'Cor Transparente' = "rgba(0,0,0,0)"
		lineageTag: 01a7ae14-e6e5-4e89-937a-1ee9840fac3f

	partition Medidas = m
		mode: import
		source =
				let
				    Fonte = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i44FAA==", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [#"tabela inicial" = _t]),
				    #"Tipo Alterado" = Table.TransformColumnTypes(Fonte,{{"tabela inicial", type text}}),
				    #"Colunas Removidas" = Table.RemoveColumns(#"Tipo Alterado",{"tabela inicial"})
				in
				    #"Colunas Removidas"

	changedProperty = Name

	annotation PBI_ResultType = Table

